/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ucampus-fake/emitir-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emitir Ticket
         * @description Paso 4 (primera mitad): UCampus genera un ticket temporal.
         */
        post: operations["emitir_ticket_ucampus_fake_emitir_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ucampus-fake/validar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validar
         * @description Pasos 5-6: el Servicio Externo consulta con el ticket y UCampus
         *     devuelve el JSON del usuario.
         *
         *     El ticket se consume: un segundo intento falla. Es lo que se espera
         *     de un token temporal, y evita que un ticket filtrado (queda en
         *     logs y en el Referer) sirva para abrir una sesión ajena.
         */
        get: operations["validar_ucampus_fake_validar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/externo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entrada Externo
         * @description Punto de entrada que UCampus llama con ?ticket=XXX.
         *
         *     IMPORTANTE: la respuesta es TEXTO PLANO, no JSON. La doc de UCampus
         *     define dos respuestas posibles:
         *       - una URL, y UCampus redirige al votante ahí;
         *       - un mensaje de error, y UCampus se lo muestra.
         *     Devolver JSON acá rompe la integración aunque el contenido sea
         *     correcto.
         */
        get: operations["entrada_externo_externo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/externo/elecciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Elecciones
         * @description Listado ya filtrado por habilitación (RF02, D-003).
         *
         *     Este es el endpoint que hoy no existe en UParticipa: el filtrado
         *     ocurre al intentar entrar a una elección concreta, no antes.
         */
        get: operations["listar_elecciones_api_externo_elecciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/externo/eleccion/{id_eleccion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle Eleccion
         * @description Detalle con preguntas y opciones, para armar la papeleta (RF03, RF04).
         */
        get: operations["detalle_eleccion_api_externo_eleccion__id_eleccion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/externo/eleccion/{id_eleccion}/urna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Urna
         * @description Urna paginada (RF10, RNF11).
         *
         *     La paginación es del servidor: traer la urna completa para mostrar
         *     50 filas anula el objetivo, y en una elección de rectoría son
         *     decenas de miles de papeletas (D-006).
         */
        get: operations["urna_api_externo_eleccion__id_eleccion__urna_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/externo/eleccion/{id_eleccion}/voto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emitir Voto
         * @description Recepción del voto ya encriptado.
         *
         *     El cuerpo esperado es {"voto_encriptado": "...", "prueba": "..."}.
         *
         *     Lo que NO recibe este endpoint es la opción elegida. El encriptado
         *     ocurre en el cliente y el servidor nunca ve el voto en claro
         *     (D-004); si acá llegara un identificador de opción, el sistema
         *     perdería la propiedad que lo justifica.
         *
         *     En el backend real este endpoint verifica la prueba de conocimiento
         *     cero antes de aceptar la papeleta. Acá solo se comprueba que el
         *     campo venga.
         */
        post: operations["emitir_voto_api_externo_eleccion__id_eleccion__voto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DetalleEleccion */
        DetalleEleccion: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "eleccion" | "consulta" | "plebiscito";
            /**
             * Estado
             * @enum {string}
             */
            estado: "en_curso" | "finalizada" | "en_pausa";
            /** Desde */
            desde: string;
            /** Hasta */
            hasta: string;
            /**
             * Claustro
             * @description Personas habilitadas para votar
             */
            claustro: number;
            /** Respuestas */
            respuestas: number;
            /**
             * Participacion
             * @description Porcentaje, 0 a 100
             */
            participacion: number;
            /** Ya Voto */
            ya_voto: boolean;
            /** Acciones */
            acciones: ("votar" | "urna" | "estadisticas" | "resultados" | "verificacion")[];
            /**
             * Seleccion
             * @enum {string}
             */
            seleccion: "simple" | "multiple";
            /** Max Selecciones */
            max_selecciones: number;
            /** Preguntas */
            preguntas: components["schemas"]["Pregunta"][];
        };
        /** FilaUrna */
        FilaUrna: {
            /**
             * Papeleta
             * @description Código de papeleta COMPLETO. Es lo que permite comprobar que un voto está en la urna, así que no se trunca.
             */
            papeleta: string;
            /** Voto Url */
            voto_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Listado */
        Listado: {
            usuario: components["schemas"]["Usuario"];
            /** Elecciones */
            elecciones: components["schemas"]["ResumenEleccion"][];
        };
        /** Opcion */
        Opcion: {
            /** Id */
            id: string;
            /**
             * Codigo
             * @description Código de la candidatura. Nulo en blanco y nulo.
             */
            codigo?: string | null;
            /** Nombre */
            nombre: string;
            /**
             * Lista
             * @description Lista a la que pertenece, si corresponde
             */
            lista?: string | null;
        };
        /**
         * PaginaUrna
         * @description Página de la urna. La paginación es del servidor: traer la urna
         *     completa para mostrar 50 filas anula el objetivo del RNF11, y en una
         *     elección de rectoría son decenas de miles de papeletas.
         */
        PaginaUrna: {
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
            /** Total */
            total: number;
            /** Total Paginas */
            total_paginas: number;
            /** Desde */
            desde: number;
            /** Hasta */
            hasta: number;
            /** Filas */
            filas: components["schemas"]["FilaUrna"][];
        };
        /** Pregunta */
        Pregunta: {
            /** Id */
            id: string;
            /** Enunciado */
            enunciado: string;
            /**
             * Opciones
             * @description En el orden en que deben mostrarse. UParticipa ofrece ver los resultados 'como se mostraron al votar', así que este orden es parte del proceso electoral y el cliente no lo reordena.
             */
            opciones: components["schemas"]["Opcion"][];
        };
        /**
         * ResumenEleccion
         * @description Proyección de una elección para el listado.
         */
        ResumenEleccion: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "eleccion" | "consulta" | "plebiscito";
            /**
             * Estado
             * @enum {string}
             */
            estado: "en_curso" | "finalizada" | "en_pausa";
            /** Desde */
            desde: string;
            /** Hasta */
            hasta: string;
            /**
             * Claustro
             * @description Personas habilitadas para votar
             */
            claustro: number;
            /** Respuestas */
            respuestas: number;
            /**
             * Participacion
             * @description Porcentaje, 0 a 100
             */
            participacion: number;
            /**
             * Ya Voto
             * @description None significa 'no informar'. El listado no expone la participación en elecciones abiertas.
             */
            ya_voto?: boolean | null;
            /** Acciones */
            acciones: ("votar" | "urna" | "estadisticas" | "resultados" | "verificacion")[];
        };
        /**
         * Usuario
         * @description Datos del votante que el módulo necesita para renderizar.
         */
        Usuario: {
            /**
             * Id Externo
             * @description Identificador del votante en UParticipa
             */
            id_externo: string;
            /**
             * Theme
             * @description Tema activo en UCampus
             */
            theme: string;
            /** Lang */
            lang: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VotoEmitido */
        VotoEmitido: {
            /** Papeleta */
            papeleta: string;
            /**
             * Reemplaza Voto Anterior
             * @description UParticipa permite volver a votar; el último voto cuenta.
             */
            reemplaza_voto_anterior: boolean;
            /** Certificado Url */
            certificado_url: string;
        };
        /**
         * VotoEntrante
         * @description Voto ya encriptado.
         *
         *     No incluye la opción elegida a propósito. El encriptado ocurre en el
         *     cliente y el servidor nunca ve el voto en claro; si acá viajara un
         *     identificador de opción, el sistema perdería la propiedad que lo
         *     justifica.
         */
        VotoEntrante: {
            /** Voto Encriptado */
            voto_encriptado: string;
            /**
             * Prueba
             * @description Prueba de conocimiento cero. En el backend real se verifica antes de aceptar la papeleta.
             */
            prueba?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    emitir_ticket_ucampus_fake_emitir_ticket_post: {
        parameters: {
            query?: {
                perfil?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validar_ucampus_fake_validar_get: {
        parameters: {
            query: {
                ticket: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entrada_externo_externo_get: {
        parameters: {
            query: {
                ticket: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_elecciones_api_externo_elecciones_get: {
        parameters: {
            query?: {
                sesion?: string | null;
            };
            header?: {
                "X-Sesion"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_eleccion_api_externo_eleccion__id_eleccion__get: {
        parameters: {
            query?: {
                sesion?: string | null;
            };
            header?: {
                "X-Sesion"?: string | null;
            };
            path: {
                id_eleccion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleEleccion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    urna_api_externo_eleccion__id_eleccion__urna_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                sesion?: string | null;
            };
            header?: {
                "X-Sesion"?: string | null;
            };
            path: {
                id_eleccion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaUrna"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emitir_voto_api_externo_eleccion__id_eleccion__voto_post: {
        parameters: {
            query?: {
                sesion?: string | null;
            };
            header?: {
                "X-Sesion"?: string | null;
            };
            path: {
                id_eleccion: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VotoEntrante"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VotoEmitido"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}